[workspace]
members = [
  "fractal_indexer",
  "fractal_math",
  "fractal_proofs",
  "fractal_sumcheck",
  "fractal_utils",
  "models"
]

[profile.release]
codegen-units = 1
lto = true

[profile.bench]
codegen-units = 1
lto = true
